language: generic
dist: xenial
sudo: required
services:
  - docker
install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
script:
  - docker build --squash -t nugulinux/sdk .
before_deploy:
  - docker images
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
deploy:
  provider: script
  script: docker push nugulinux/sdk
  on:
    all_branches: true
